server:
  port: 8080
  servlet:
    context-path: /


#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: =/h2-console

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres


  flyway:
    locations: classpath:db/migration

#    url: jdbc:postgresql://awseb-e-wnmmav6frc-stack-awsebrdsdatabase-wzgyetf7wu7n.cnmotrz9ecjh.eu-central-1.rds.amazonaws.com:5432/ebdb
#    username: kastkest
#    password: rerecbrb

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
#jwt:
#  secret: \jsdfjasdfjakjsd;flka;slkfoaisp;flkdsafkdksfkas;flklsjdfkjhskdjhfkjshfdkjhfskj
#  lifetime: 360000
